### ISSUE TITLE
Convert "if"(conditional logic) is not supported

### ISSUE THREAD

**Issue by yassan** [rancher/migration-tools#13]
For the following `docker-compose.yml.tpl` ,

ex) [traefik/community-catalog](https://github.com/rancher/community-catalog/blob/78998c404e500e9170a7a086ee908cd28b0e6fdf/templates/traefik/28/docker-compose.yml.tpl#L1-L31)
```YAML
version: '2'
services:
  traefik:
    ports:
    - ${admin_port}:${admin_port}/tcp
    - ${http_port}:${http_port}/tcp
  {{- if ne .Values.https_enable "false"}}
    - ${https_port}:${https_port}/tcp
  {{- end}}
    labels:
```

The following error message appears.

```
[ERROR] Parsing docker compose files: Failed to parse the docker-compose yaml file, error: yaml: line 7: could not find expected ':'
```

Would you support "if"(conditional logic) ?
Or Is there any better way to do this?

Thank you.

**Environment**

- migration-tools v0.1.1
